### ISSUE TITLE
error to login .

### ISSUE THREAD

**Issue by fediralydev** [urdadx/librelinks#54] opened 2023-12-02 20:33 UTC
### Description

i dont know where problem someone can help me 
![Screenshot 2023-12-02 at 9 33 13 PM](https://github.com/urdadx/librelinks/assets/109765255/083624a4-9fab-4146-97da-088d5be6a76c)

### Screenshots (if applicable)

![Screenshot 2023-12-02 at 9 32 20 PM](https://github.com/urdadx/librelinks/assets/109765255/f1e83caf-594f-4a71-89ea-879cb3b86855)

### Affected Browser

Chrome

### Checklist

- [X] Checked for similar issues
- [X] Willing to work on this issue (optional)

**Comment by urdadx** [comment] 2023-12-20 18:50
Hey @fediralydev sorry for the late reply, I have been busy with school work.
 

I think the "DNS resolution" error typically indicates that there's an issue resolving the host name to an IP address. Ensure your MongoDB connection string is correct and that your network settings allow DNS resolution. Double-check the Prisma configuration and Next.js environment variables for any typos or misconfigurations. If the issue persists, consider checking your internet connection and DNS settings.

Also make sure to add 0.0.0.0 to the list of whitelist IP addresses in your Atlas dashboard.

Since I can't reproduce the error on my end, this is all I can do to help you.

I will be closing the other issue you opened since it's a duplicate of this.

**Comment by fediralydev** [comment] 2023-12-20 18:52
Hey i fix but i talk now about deploying this project to host for example i
have cpanel but I don’t having node js ?

**Comment by urdadx** [comment] 2023-12-20 18:54
I don't understand what you're trying to say. What is cpanel and where are you deploying it

**Comment by fediralydev** [comment] 2023-12-20 18:59
ok look first problem  look in screenshot - 2 problem i have server with
cpanel like in aeon free host i can't upload this in my file manager ??

**Comment by urdadx** [comment] 2023-12-20 19:04
Unfortunately, I haven't hosted any projects on cpanel before so I don't know how to help you.

However, you can try deploying on [Vercel](vercel.com) since that's what I used to deploy this project

**Comment by fediralydev** [comment] 2023-12-20 19:06
okay see the screenshot  about problem tokken analytics....

**Comment by urdadx** [comment] 2023-12-20 19:12
@fediralydev, if you want the analytics feature to work, you need to get a token  from [TinyBird](tinybird.co).

Without it, it won't work. Please go to the Tinybird website for more information on this.

I will be closing this issue since your questions are not related to contributing to the project. Thank you.

**Comment by fediralydev** [comment] 2023-12-20 19:14
i go but can you help give me step by step !

**Closed as completed** 2023-12-20 19:15 UTC

**Comment by fediralydev** [comment] 2023-12-20 19:17
??
